### PR TITLE
Hungarian language added

### PR DESCRIPTION
**Pull request by PiciAkk**
I added a basic boilerplate for the Hungarian language, and uploaded some jokes. I also extended the documentation with information about using pyjokes with the Hungarian language

### CODE REVIEW

**Comment by alexsavio** [comment]
LGTM!

**Comment by PiciAkk** [comment]
@alexsavio Will you merge it?

**Comment by alexsavio** [comment]
Happy New Year! Thank you!

**Comment by PiciAkk** [comment]
Happy New Year!

**Pull request merged**
