### PR TITLE
Added more spanish jokes, without my git client messing around and ad…

### PR DESCRIPTION
**Pull request by ResonantWave**
…ding things where it shouldn't.

Hope it doesn't break everything this time!

### CODE REVIEW

**Comment by ResonantWave** [comment]
Should I remove special chars like¿ and ¡? It seems that they make the program fail

**Comment by bennuttall** [comment]
I think so. @oiertwo will be able to tell you!

**Comment by bennuttall** [comment]
Also, what is a git client?

**Comment by ResonantWave** [comment]
A git client is for example this: http://www.syntevo.com/smartgit/ (It's the one I'm using). I'm just trying it, but I think I'll switch back to the cli.

**Comment by oiertwo** [comment]
I think now its ok. 

Prev explanation: In the windows console the Spanish accents and special chars (¿, ¡, ñ ...) cannot be displayed properly with utf-8, so until we fix the problem we are removing them from our jokes.

**Pull request merged**
