### PR TITLE
Added Runtime Joke

### PR DESCRIPTION
**Pull request by jxu093**
funny?

### CODE REVIEW

**Comment by bennuttall** [comment]
What do you mean by running time? uptime would work

**Comment by jxu093** [comment]
amount of time running/exercising lol

**Comment by yashmehrotra** [comment]
@jxu093 How is it related to programming ? running time == uptime of server ?

**Comment by jxu093** [comment]
https://en.wikipedia.org/wiki/Time_complexity

**Comment by yashmehrotra** [comment]
So I Think you are referring that: So fat -> Big O complexity , with O referring to how fat she is and looking similar to zero ? I am sorry If I misunderstood this one

**Comment by bennuttall** [comment]
Shall we just go with uptime?

**Comment by acz13** [comment]
I think this joke means that she doesn't **run** as in **run** a marathon. Not sure though.

**Comment by yashmehrotra** [comment]
@bennuttall I don't think he meant that uptime reference

**Comment by alexsavio** [comment]
So, any comments here? Has anyone got the joke?

**Comment by alexsavio** [comment]
Apart from the subjectivity on the quality of the joke, it still needs a break point in the end. Please...

**Comment by alexsavio** [comment]
@jxu093 could you please add the '.' in the end? O should I close this PR? Thanks!

**Comment by alexsavio** [comment]
@jxu093 could you please solve the conflict? thank you!

**Comment by alexsavio** [comment]
Sorry this got old, please open a new PR if you still want this merged.

**Pull request closed without merging**
