### PR TITLE
initial support cs-cz language

### PR DESCRIPTION
**Pull request by Manasovo**

### CODE REVIEW

**Comment by bennuttall** [comment]
Can somebody czech these jokes are funny?

**Comment by Manasovo** [comment]
of course there are funny ... otherwise i wouldn't put them there :-)

**Comment by Tony763** [comment]
Jokes are OK, no racism or sexist.  And Yes, they are funny.

**Comment by nextsux** [comment]
Any news? Also looking for this to be merged

**Comment by alexsavio** [comment]
Sorry, I know this got old, would you have time to fix the conlicts, or let me fix them?

**Pull request merged**
