### PR TITLE
Replace scripts with console_scripts entry point

### PR DESCRIPTION
**Pull request by thurask**
Replaces scripts config in setup.py with entry_point. Moves contents of scripts/ into pyjokes/cmdparse.py.

Gets the script working on Windows, incidentally.

Tests are all still 100%.

### CODE REVIEW

**Comment by yashmehrotra** [comment]
@thurask Can you squash your commits to 1 commit. It looks much cleaner.

**Comment by thurask** [comment]
Will squash commits later today.

**Comment by thurask** [comment]
OK, done.

**Comment by bennuttall** [comment]
@oiertwo you coverage has fallen with this PR so I'll leave to you to sort out.

**Comment by alexsavio** [comment]
need help?

**Comment by bennuttall** [comment]
Can we get this merged @oiertwo?

**Comment by alexsavio** [comment]
It looks good to me. :+1:

**Pull request closed without merging**
