### PR TITLE
quick and simple auto joke generator

### PR DESCRIPTION
**Pull request by chozabu**
Inspired by lightning talk man, and some really bad jokes, I present the pyjoke "auto" module - which can already generate 10000+ original jokes! A few of them may even be funny. perhaps.

### CODE REVIEW

**Comment by chozabu** [comment]
And here is some of the output...

can you make a bear learn assembly? PARSE ERROR
why did the chicken learn assembly? PARSE ERROR
would a chicken go to a bar? no
why did the german tell a good joke? PARSE ERROR
why did the scotsman tell a good joke? german sex
ever seen a java programmer play pong? to get to the other side
would a code monkey get really clean? for the interview
ever seen a python programmer tell a bad joke? yes
can you make a scotsman play pong? no
would a german cross the road? to get to the other side
can you make a java programmer eat cheese? yes
would a irishman say sorry? sex
can you make a englishman tell a good joke? for the interview
ever seen a englishman cross the road? sex
ever seen a java programmer play pong? to get to the other side
would a pope get really clean? german sex
would a code monkey get really clean? for the interview
would a irishman say sorry? sex
why did the barman play pong? sex
would a chicken go to a bar? no
would a pope get really clean? german sex
would a german cross the road? to get to the other side
ever seen a scotsman say sorry? german sex
ever seen a scotsman go to a bar? for the interview

**Comment by oiertwo** [comment]
I do not know this is something should go inside pyjokes... maybe as an external app/plugin/extension? @bennuttall @alexsavio @borjaayerdi thoughts?

**Comment by chozabu** [comment]
I'd actually agree it probably should not be merged, at least not without some serious alterations/upgrades - which I am not intending on doing.

On a mostly unrelated side note, and as a shameless plug, I did a quick joke app of a different nature here: https://github.com/chozabu/HeavyMouse

**Comment by alexsavio** [comment]
Thanks for the suggestion, but in the beginning of the project we had some automations, but we discarded them.

**Pull request closed without merging**
