### PR TITLE
Add some French jokes

### PR DESCRIPTION
**Pull request by alfreddagenais**
My contribution of french jokes

### CODE REVIEW

**Comment by alexsavio** [comment]
LGTM! I think we should merge! Thank you!

**Comment by apennamen** [comment]
Hello,
Mycroft.ai joke skill rely on this project to tell jokes. As there are still no french jokes added (at least a first round), it fails...
Could we at least merge this work from alfreddagenais ?
Regards,
AP

**Comment by vpoulailleau** [comment]
Hi, thanks for this contribution, we're missing french jokes. Just one remark though, in french there is a mandatory non-breakable space before every !?:;

Some of them are missing.

**Comment by alfreddagenais** [comment]
@vpoulailleau Il follow somes rules from https://www.btb.termiumplus.gc.ca/redac-chap?lang=fra&lettr=chapsect6&info0=6.13 https://vitrinelinguistique.oqlf.gouv.qc.ca/index.php?id=22039 

For me seem not required, but I think i am confused with some rules 🤔 What do you think about this rules? Or have you other link to give me indications

Thank you 😃

**Comment by vpoulailleau** [comment]
@alfreddagenais I don't know the Canadian rules you provided, maybe they are different. I was suggesting the French ones that are explained here for instance:

- http://www4.ac-nancy-metz.fr/ien-vittel/docs%20site/outils%20pour%20le%20maitre/regles_typo_version2012.pdf
- https://jacques-andre.fr/faqtypo/lessons.pdf
- https://archive.framalibre.org/article2225.html#d_ponctuation_bis

**Pull request merged**
