### PR TITLE
Added Swedish jokes

### PR DESCRIPTION
**Pull request by michjnich**
I've added some jokes in Swedish - some don't pass the test cases because they have Swedish letters in them (ä, å or ö), though some seem to - not sure why some are OK and some aren't. The ones that cause the test cases to fail are commented out. They're all "clean" jokes - I left out the ones that weren't. Credit for the source is given in a comment in the Swedish file. //Mike

### CODE REVIEW

**Comment by alexsavio** [comment]
Do you swear there are no adult jokes here? :)

**Comment by michjnich** [comment]
Nope, I filtered out the adult ones and removed them :) The most "offensive" joke is the one poking fun at the Norwegians - Swedes and Norwegians have a friendly rivalry: 

"Jag är ett Norskt virus. Var vänlig och skicka vidare mig till alla i din adressbok. Radera sedan alla dina filer på hårddisken."

=> "I am a Norwegian virus. Please send me all the contacts in your address book and then delete all the files on your hard-drive".

**Comment by michjnich** [comment]
Hi. Sorry, I'd completely missed your comment ... things have been a little hectic over here recently, so please go ahead and sort the conflicts if you have a little time.

**Comment by michjnich** [comment]
OK, sorry about the irrelevant PR I created - I've not actually tried to fix merge conflicts on an old branch across forks before :) 

Anwyay, I think this should be OK to merge now!

**Comment by alexsavio** [comment]
Thank you!

**Pull request merged**
