### PR TITLE
Add French jokes

### PR DESCRIPTION
**Pull request by bennuttall**
I've created the boilerplate for adding French jokes to pyjokes in the french branch. If anyone wants to submit French jokes there, please do!

There's no need to translate all the English jokes into French, as I'm sure that won't work much of the time, but feel free to use any that will work in French.

@matrixise - maybe you can help?

PS (Pyjokes Society): Don't merge this PR until it's ready!

### CODE REVIEW

**Comment by matrixise** [comment]
great, thanks @bennuttall

**Comment by alexsavio** [comment]
Quand votre marteau est C ++, tout commence de ressembler à une pouce.

**Comment by Killmax** [comment]
"A coder sans péril, on commit sans gloire." (copyright to CommitStrip)

**Comment by alexsavio** [comment]
Could anyone please resolve the conflicts?

**Comment by alfreddagenais** [comment]
I do a PR with this branch on https://github.com/pyjokes/pyjokes/pull/91

**Pull request closed without merging**
