### PR TITLE
Joke for jokes_en.py

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: Gowtham Shanmugasundaram <gowthamjayam93@gmail.com>

### CODE REVIEW

**Comment by alexsavio** [comment]
Please fix the typos in the joke.

**Comment by GowthamShanmugam** [comment]
> Please fix the typos in the joke.

done

**Comment by GowthamShanmugam** [comment]
@alexsavio Please review

**Comment by alexsavio** [comment]
What is a KT session?

**Comment by GowthamShanmugam** [comment]
@alexsavio Please review

> What is a KT session?

knowledge transfer session

**Comment by alexsavio** [comment]
Could you please replace KT by its meaning? Also, the punctuation needs to
be fixed.

**Comment by GowthamShanmugam** [comment]
@coveralls done with the changes

**Comment by alexsavio** [comment]
Thank you!

**Pull request merged**
