### PR TITLE
Why do programmers prefer dark mode?

### PR DESCRIPTION
**Pull request by vpoulailleau**
Because light attracts bugs.

### CODE REVIEW

**Comment by Petint** [comment]
So true.

**Comment by ciw79-de** [comment]
@alexsavio @bennuttall @borjaayerdi @oiertwo :
Look like this project is no longer maintained? There are a couple of pending pull requests. Is there anything I could help with?

**Comment by Petint** [comment]
@ciw79-de Hi Chris! I'm the maintainer of the only major pyjokes fork. I myself haven't had much time to work on it myself. But feel free to contribute there. 73 de HA5KPI

**Comment by alexsavio** [comment]
Hi! Yes, the team doesn't have much time anymore to work here. Any interest on helping out?

**Comment by ciw79-de** [comment]
Yes sure. Would be great to bring the pending PRs into a new version.
How should I get started?

**Comment by Petint** [comment]
@ciw79-de You could help me with making sure that all jokes in the vpoulailleau-patch-1 branch pass the tests, so we may pull it into the master branch. I would appreciate that.

**Comment by ciw79-de** [comment]
@Petint that only makes sense if eventually your fork can be merged into the master branch and a new version can be released. Otherwise I don't see a point in merging your branch, so I would first like to ensure that there is a way to achieve these points.

**Comment by Petint** [comment]
@ciw79-de I'm talking about the master brance on petint/pyjokes. But on the topic of  merging into the master branch (of thos repo) I actually Already have a [pull request](https://github.com/pyjokes/pyjokes/pull/106 ) and am fully planning to do so.
I only made a fork because the new Hungarian jokes weren't included in the tests. Then it grew on me.

**Comment by alexsavio** [comment]
LGTM! Thanks for the funny joke!

**Pull request merged**
