### PR TITLE
added SEO joke (Fixed previous one)

### PR DESCRIPTION
**Pull request by Achifaifa**
This one is a classic.

I also fixed my previous joke, the BC was obviously wrong. Woops.

### CODE REVIEW

**Comment by bennuttall** [comment]
You forgot the comma on the end of the COBOL joke.

Should it not be 9999AD?

**Comment by Achifaifa** [comment]
I've always used CE (Current/Common Era), but whatever works best. I'm not picky :)

**Comment by bennuttall** [comment]
So he is travelling into the future, right?

I think the wording "the year is now 9999" makes enough sense.

**Comment by Achifaifa** [comment]
Yeah, the idea is that he gets frozen and is awaken in a future time. Kinda hard to put that joke in 140 chars :/

**Pull request closed without merging**
