### PR TITLE
Add Dark Jokes

### PR DESCRIPTION
**Pull request by skywalkeretw**
Add list of dark english Jokes from [dark-humor-jokes](https://parade.com/1295709/marynliles/dark-humor-jokes/) 
Add dark as  categorie

### CODE REVIEW

**Comment by skywalkeretw** [comment]
Greate Module would love to contribute some dark humor to the mix :)

**Comment by skywalkeretw** [comment]
@bennuttall a code review and approve would be much obliged.

**Comment by alexsavio** [comment]
Could you please add a test for this category?

**Comment by bennuttall** [comment]
We've decided not to accept this as we'd like to keep the library to just programmer jokes. We'll remove the chuck norris jokes too.

Sorry/thanks

**Pull request closed without merging**
